// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwoqchlkvveqjfvtcbmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3b3FjaGxrdnZlcWpmdnRjYm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTkzMjgsImV4cCI6MjA2ODQ5NTMyOH0.kxqVjyIKzbpC-nsTdMPg1aq0DKnfn0dntVpPqrI0up8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});